// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsNzcH7v0tyyg_LjB8i1rHPNgXb45bKWY',
    appId: '1:131764292652:web:dc7052469f5dc89803d589',
    messagingSenderId: '131764292652',
    projectId: 'chat-app-61351',
    authDomain: 'chat-app-61351.firebaseapp.com',
    storageBucket: 'chat-app-61351.firebasestorage.app',
    measurementId: 'G-70T2LGQ74H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUK8wUW0EuvCmRkPh0NuW01yL16D_ddxo',
    appId: '1:131764292652:android:2e00659877f1d9ee03d589',
    messagingSenderId: '131764292652',
    projectId: 'chat-app-61351',
    storageBucket: 'chat-app-61351.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUCTWnXIHjlATd3xFfknK_dVi8O5qF8tE',
    appId: '1:131764292652:ios:f2015c52054b668803d589',
    messagingSenderId: '131764292652',
    projectId: 'chat-app-61351',
    storageBucket: 'chat-app-61351.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUCTWnXIHjlATd3xFfknK_dVi8O5qF8tE',
    appId: '1:131764292652:ios:f2015c52054b668803d589',
    messagingSenderId: '131764292652',
    projectId: 'chat-app-61351',
    storageBucket: 'chat-app-61351.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsNzcH7v0tyyg_LjB8i1rHPNgXb45bKWY',
    appId: '1:131764292652:web:7f192d6de2d4d90003d589',
    messagingSenderId: '131764292652',
    projectId: 'chat-app-61351',
    authDomain: 'chat-app-61351.firebaseapp.com',
    storageBucket: 'chat-app-61351.firebasestorage.app',
    measurementId: 'G-WSX2T9Z4KN',
  );
}
